FROM eclipse-temurin:21-jdk-jammy

WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY .mvn .mvn
COPY mvnw pom.xml ./

RUN chmod +x mvnw

ENV MAVEN_OPTS="-Dmaven.repo.local=/root/.m2/repository"

RUN ./mvnw dependency:go-offline

EXPOSE 8080

COPY entrypoint.sh ./
RUN chmod +x entrypoint.sh

CMD ["bash", "./entrypoint.sh"]